[project]
name = "agent"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "AFuture", email = "afuture.d@outlook.com"},
]
dependencies = [
    "django>=5.0.6",
    "psycopg[binary]>=3.1.19",
    "python-dotenv>=1.0.1",
    "OpenAI>=1.30.1",
    "pgvector>=0.2.5",
    "tiktoken>=0.7.0",
    "django-ninja>=1.1.0",
    "cohere>=5.5.4",
    "koma @ file:///${PROJECT_ROOT}/../pkg-core",
    "uvicorn[standard]>=0.30.1",
]
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true

[tool.pdm.build]
excludes = ["./**/.git"]


[tool.pdm.scripts]

migrate = "python ./manage.py migrate rag"
server = "uvicorn agent.asgi:application --host 0.0.0.0"

[tool.pytest]
DJANGO_SETTINGS_MODULE="agent.settings"