[project]
name = "loci"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "AFuture", email = "afuture.d@outlook.com"},
]
dependencies = [
    "protobuf>=5.26.1",
    "sqlalchemy[asyncio]>=2.0.30",
    "psycopg[binary]>=3.1.19",
]
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project.scripts]
qa = "q:cli"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "DEBUG"
